cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check cockroachdb [x86_64-linux]",
  "check kld [x86_64-linux]",
  "check kld-benches [x86_64-linux]",
  "check kld-clippy [x86_64-linux]",
  "check kld-mgr [x86_64-linux]",
  "check kld-mgr-clippy [aarch64-darwin]",
  "check kld-mgr-clippy [x86_64-linux]",
  "check kld-mgr-tests [x86_64-linux]",
  "check kld-tests [x86_64-linux]",
  "check treefmt [x86_64-linux]",
  "devShell default [x86_64-linux]",
  "package bitcoind [x86_64-linux]",
  "package cockroachdb [x86_64-linux]",
  "package default [x86_64-linux]",
  "package kld [x86_64-linux]",
  "package kld-mgr [aarch64-darwin]",
  "package kld-mgr [x86_64-linux]",
  "package remote-pdb [x86_64-linux]"
]
