[package]
name = "lightning-knd"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".",
    "bitcoind",
    "database",
    "logger",
    "settings",
    "test-utils"
]

[[bin]]
name = "lightning-knd"
path = "src/main.rs"

[dependencies]
bitcoind = { path = "bitcoind" }
logger = { path = "logger" }
settings = { path = "settings" }
database = { path = "database" }
lightning = { version = "0.0.112", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.112", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.20" }
lightning-net-tokio = { version = "0.0.112" }
lightning-persister = { version = "0.0.112" }
lightning-background-processor = { version = "0.0.112" }
lightning-rapid-gossip-sync = { version = "0.0.112" }

bitcoin = "0.29.2"
bitcoin-bech32 = "0.12"
bech32 = "0.9"
hex = "0.4"

anyhow = { version = "1.0.66", features = [ "backtrace" ] }
futures = "0.3"
chrono = "0.4"
rand = "0.8.5"
log = { version = "0.4", features = ["std"] }
tokio = { version = "1", features = [ "full" ] }
prometheus = "0.13.2"
once_cell = "1.16.0"
hyper = { version = "0.14.20", features = [ "full" ] }

[dev-dependencies]
test-utils = { path = "./test-utils" }
reqwest = { version = "0.11", default-features = false }
