[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.16.0"
clap = { version = "4.0.32", features = ["derive", "env"] }
bitcoin = "0.29.2"

[lib]
doctest = false
