[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
lightning = { version = "0.0.113", features = ["max_level_trace"] }
log = { version = "0.4", features = ["std"] }
once_cell = "1.17.0"
anyhow = { version = "1.0.69", features = [ "backtrace" ] }

[lib]
doctest = false
