[package]
name = "kld"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kld"
path = "src/main.rs"

[[bin]]
name = "kld-cli"
path = "src/cli/main.rs"

[lib]
doctest = false

[dependencies]
api = { path = "../api" }
settings = { path = "../settings" }
lightning = { version = "0.0.115", features = ["max_level_trace", "_test_utils"] }
lightning-block-sync = { version = "0.0.115", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.23" }
lightning-net-tokio = { version = "0.0.115" }
lightning-background-processor = { version = "0.0.115", features = [ "futures" ] }
lightning-rapid-gossip-sync = { version = "0.0.115" }

macaroon = "0.3.0"
bitcoin = "0.29.2"
bitcoincore-rpc-json = "0.16.0"
rust-bip39 = "1.0.0"
hex = "0.4"
base64 = "0.21.0"
# see https://github.com/bitcoindevkit/bdk/pull/850, rebased to 0.27.1 release
#bdk = { version = "0.26.0", features = [ "rpc" ] }
bdk = { git = "https://github.com/JosephGoulden/bdk", branch = "backport-begin-batch-result", features = [ "rpc" ] }
anyhow = { version = "1.0.71", features = [ "backtrace" ] }
futures = "0.3"
chrono = "0.4"
rand = "0.8.5"
log = { version = "0.4", features = ["std"] }
tokio = { version = "1", features = [ "full" ] }
prometheus = "0.13.2"
once_cell = "1.17.1"
hyper = { version = "0.14.26", features = [ "full" ] }
serde = "1.0"
serde_json = "1.0"
axum = { version = "0.6.18", features = ["ws", "headers"] }
axum-server = { version = "0.5", features = ["tls-rustls"] }
tower-http = { version = "0.4.0", features = [ "cors" ] }
async-trait = "0.1.68"
clap = { version = "4.2.7", features = ["derive", "env"] }
reqwest = { version = "0.11", features = [ "blocking", "native-tls", "json" ] }

bitvec = "1.0.1"
tokio-postgres = { version = "0.7.8", features = ["runtime", "with-bit-vec-0_6", "with-uuid-0_8"] }
postgres-openssl = "0.5.0"
openssl = "0.10.52"
refinery = { version = "0.8.9", features = [ "tokio-postgres" ] }

[dev-dependencies]
test-utils = { path = "../test-utils" }
criterion = { version = "0.4.0", features = ["async_tokio"] }



