[zh_TW]
"Command List" = "å‘½ä»¤åˆ—è¡¨"
"History" = "æ­·å²è¨˜éŒ„"
"Node" = "ç¯€é»"
"information" = "è³‡è¨Š"
"NodeInfo" = "ç¯€é»è³‡è¨Š"
"fees" = "è²»ç”¨"
"NodeFees" = "ç¯€é»è²»ç”¨"
"estimate liquidity" = "ä¼°è¨ˆæµå‹•æ€§"
"NodeEslq" = "ä¼°è¨ˆæµå‹•æ€§"
"sign" = "ç°½å"
"NodeSign" = "ç°½å"
"list funds" = "åˆ—å‡ºè³‡é‡‘"
"NodeLsfd" = "åˆ—å‡ºè³‡é‡‘"
"Network" = "ç¶²è·¯"
"list nodes" = "åˆ—å‡ºç¯€é»"
"NetwLsnd" = "åˆ—å‡ºç¯€é»"
"fee rates" = "è²»ç‡"
"NetwFeer" = "æŸ¥è©¢è²»ç‡"
"Peers" = "åŒå„•ç¯€é»"
"Public Key" = "å…¬é–‹é‘°åŒ™"
"list" = "åˆ—å‡º"
"PeerList" = "åˆ—å‡ºåŒå„•ç¯€é»"
"connect" = "é€£æ¥"
"PeerCont" = "é€£æ¥åŒå„•ç¯€é»"
"disconnect" = "ä¸­æ–·"
"PeerDisc" = "ä¸­æ–·é€£æ¥"
"Payments" = "ä»˜æ¬¾è³‡è¨Š"
"PaymList" = "åˆ—å‡ºä»˜æ¬¾è³‡è¨Š"
"send key" = "ç™¼é€å…¬é‘°"
"PaymSdky" = "ç™¼é€å…¬é‘°"
"pay invoice" = "æ”¯ä»˜ç™¼ç¥¨"
"PaymPayi" = "æ”¯ä»˜ç™¼ç¥¨"
"Invoices" = "ç™¼ç¥¨"
"InvoList" = "åˆ—å‡ºç™¼ç¥¨"
"generate" = "ç”Ÿæˆ"
"InvoGene" = "ç”Ÿæˆç™¼ç¥¨"
"decode" = "è§£ç¢¼"
"InvoDeco" = "ç™¼ç¥¨è§£ç¢¼"
"Channels" = "é€šè·¯"
"ChanList" = "åˆ—å‡ºé€šè·¯"
"open" = "æ‰“é–‹"
"ChanOpen" = "æ‰“é–‹é€šè·¯"
"set fee" = "è¨­å®šè²»ç”¨"
"ChanSetf" = "è¨­å®šè²»ç”¨"
"close" = "é—œé–‰"
"ChanClos" = "é—œé–‰é€šè·¯"
"history" = "æ­·å²è³‡è¨Š"
"ChanHist" = "é€šè·¯æ­·å²"
"balance" = "é¤˜é¡"
"ChanBala" = "é€šè·¯é¤˜é¡"
"list forwards" = "è½‰å¯„æ¸…å–®"
"ChanLsfd" = "é€šè·¯è½‰å¯„æ¸…å–®"
"Query at " = "æŸ¥è©¢æ–¼"
"Press " = "å£“ä¸‹"
"Then, press " = "å†æ¬¡å£“ä¸‹"
" to fetch again" = "ä»¥å†æ¬¡ç²å–è³‡è¨Š"
" to fetch" = "ä»¥ç²å–è³‡è¨Š"
" to input data.  " = "ä»¥è¼¸å…¥è³‡æ–™"
" again to execute.  " = "ä¾†åŸ·è¡Œ"
"On query, please wait..." = "æŸ¥è©¢ä¸­ï¼Œè«‹ç¨å¾…..."
"Can not find out previous query." = "ç„¡å…ˆå‰æŸ¥è©¢è³‡è¨Š"
"Fail to connect on DB." = "ç„¡æ³•è¯çµè³‡æ–™åº«"
"Welcome to ğŸŒ”kuutamo Tui" = "æ­¡è¿ä½¿ç”¨ğŸŒ”kuutamo Tui"
"Following are the key setting you are using now" = "ä»¥ä¸‹æ˜¯æ‚¨ç¾åœ¨æ­£ä½¿ç”¨çš„æŒ‰éµè¨­å®š"
"If you have any suggestion please let us know on Github." = "å¦‚æœæ‚¨æœ‰ä»»ä½•å»ºè­°æ­¡è¿åœ¨Githubä¸Šèˆ‡æˆ‘å€‘è¯ç¹«"
"Introduction" = "èªªæ˜"
" to cancel inputs.  " = "ä»¥å–æ¶ˆè¼¸å…¥"
"Decode response error:" = "å›æ‡‰è§£è­¯éŒ¯èª¤ï¼š"

[en_US]
"NodeInfo" = "Node Information"
"NodeFees" = "Node Fees"
"NodeEslq" = "Estimate Liquidity"
"NodeSign" = "Sign"
"NodeLsfd" = "List Funds"
"NetwLsnd" = "List Nodes"
"NetwFeer" = "Fee Rates"
"PeerList" = "List Peer"
"PeerCont" = "Connect"
"PeerDisc" = "Disconnect"
"PaymList" = "List Payments"
"PaymSdky" = "Send Key"
"PaymPayi" = "Pay Invoices"
"InvoList" = "List Invoices"
"InvoGene" = "Generate Invoice"
"InvoDeco" = "Decode invoice"
"ChanList" = "List Channels"
"ChanOpen" = "Open Channel"
"ChanSetf" = "Set Fee"
"ChanClos" = "Close Channel"
"ChanHist" = "Channel History"
"ChanBala" = "Channel Balance"
"ChanLsfd" = "List Forwards"
